USE master
GO
CREATE DATABASE Blog
GO
USE Blog
GO

CREATE TABLE Users (
    IDUsers INT IDENTITY(1,1) PRIMARY KEY,
    Username NVARCHAR(255) NOT NULL,
    Password NVARCHAR(255) NOT NULL,
    Email NVARCHAR(255) NOT NULL
)
GO

CREATE TABLE BlogPosts (
    IDBlogPosts INT IDENTITY(1,1) PRIMARY KEY,
    Title NVARCHAR(255) NOT NULL,
    Content TEXT NOT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
    UpdatedAt DATETIME NOT NULL DEFAULT GETDATE(),
    UserID INT NOT NULL,
    FOREIGN KEY (UserID) REFERENCES Users(IDUsers)
)
GO

CREATE TABLE Comments (
    IDComments INT IDENTITY(1,1) PRIMARY KEY,
    Content TEXT NOT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
    UpdatedAt DATETIME NOT NULL DEFAULT GETDATE(),
    UserID INT NOT NULL,
    BlogPostsID INT NOT NULL,
    FOREIGN KEY (UserID) REFERENCES Users(IDUsers),
    FOREIGN KEY (BlogPostsID) REFERENCES BlogPosts(IDBlogPosts)
)
GO
